version: "3.7"
services:
  postgresqldb:
    image: postgres:latest
    container_name: taskapidatabase
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_USER=postgres
      - POSTGRES_DB=db_desafio_accenture

  api:
    image: tasks-api:latest
    container_name: tasks-api
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - postgresqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://taskapidatabase:5432/db_desafio_accenture
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=docker