spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate

  datasource:
    platform: postgres
    username: postgres
    password: postgres
    url: jdbc:postgresql://taskapidatabase:5432/db_desafio_accenture
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: true

  flyway:
    clean-disabled: false
    clean-on-validation-error: false
    table: migrations_history
    locations:
      - classpath:database/migrations